### ISSUE TITLE
petite suggestion?

### ISSUE THREAD

**Issue by persianphilosopher** [Fukotaku/fufu#5]
Avant une petite suggestion, je tiens à vous remercier pour ce repo Slim  pour son originalité, en particulier les commandes de console. Je suis avec plaisir le développement depuis 1.0.3.

J’ai une petite proposition ou suggestion que j’ai longuement hésité à vous faire puisqu’elle ne fait pas partie de votre roadmap/objectifs. J’espère au moins que vous ne m’en voudrez pas pour la mentionner. 

C’est le mot-clef csrf qui m’a fait découvrir votre projet et c’est son intégration avec un simple login qui m’embête depuis des mois. Il y a bien entendu pas mal de repos Slim sur GitHub avec un système d’authentification. Mais je n’ai pas encore trouvé un modèle qui combine bien la csrf, login, et ajax requests. J’ai un petit appli pour prendre des notes (markdown). Sans login, j’arrive à bien faire fonctionner ajax et csrf. Avec login, c’est pas toujours évident. En suivant GitHub et des différents forums, je sais que je ne suis pas le seul à avoir ce souci. 

En un mot ou deux, puisque vous prenez tant de soins avec vos middlewares, je pensais que vous pourriez peut-être guider le reste d’entre nous amateurs-bricoleurs de Slim.

Je comprendrais tout à fait si cette suggestion ne vous intéresse pas. En tout cas, merci pour vos efforts et vos partages.

**Comment by Fukotaku** [comment]
En effet, je donne peu d'explication sur les middlewares/functions déjà présent sur mon skeleton et j'y est pensé pendant un moment.

Mais vu que j'ai créer ce skeleton surtout pour moi je ne m'attendais pas que quelqu'un aurais commencé à suivre et être intéressé assé vite, je pense en effet me mettre à la tâche, faire un fichier markdown avec quelques explications sur ce qui est déjà présent pour guider les futurs utilisateurs sur l'architecture, l'organisation ect...

Je te le dis avec sincérité, je ne dispose pas forcément toujours le temps et l'envie de faire ça, mais un moment viendra oui ! 

Pour ton problème de csrf, depuis ma release 1.0.3 j'ai ajouté un middleware et fonction pour la gestion de token, car vu que je ne maitrise pas encore très bien le middleware csrf de slim pour les requêtes get, j'ai créé la mienne, et qui peux servir aussi pour les requêtes ajax.

Un grand merci pour l'intêret que tu porte à mon projet et à ton message ! :+1:

**Comment by Fukotaku** [comment]
J'ai commencé à écrire un petit guide d'utilisation sur la branch `develop`, je t'invite à aller regarder d'ici quelques heures pour me donner ton avis.
En attendant, tu peux aller regarder mon skeleton [fufu2](https://github.com/Fukotaku/fufu2) ;)

**Comment by persianphilosopher** [comment]
Merci beaucoup!
